---
- hosts: all
  remote_user: oliver
  # NOTE: Run this with ansible-playbook -become -i home_cluster.ini cluster_packages_u2204.yaml
  # become: true
  # become_method: sudo
  # become_user: root
  tasks:
    - copy: src=files/resolv.conf dest=/etc/resolv.conf
    - file: path=/etc/localtime state=absent
    - file: path=/etc/localtime src=/usr/share/zoneinfo/America/Toronto state=link
    - file: path=/etc/netplan/00-installer-config.yaml state=absent
    - file: path=/mnt/shared_storage state=directory
    
    - name: clean the 127.0.1.1 self reference that messes up slurm
      shell: 
        cmd: sed -i '/^127.0.1.1/d' /etc/hosts
    
    - name: Ensure that common packages are installed
      apt: name={{item}} state=present
      with_items:
        - ntp
        - nfs-common

    - service: name=ntp state=started enabled=yes

    - name: Ensure that IPv6 is disabled
      copy: src=files/disable-ipv6.conf dest=/etc/modprobe.d owner=root group=root mode=0644

- hosts: compute
  remote_user: oliver
  tasks:
    - name: Add NFS mount to /etc/fstab
      ansible.builtin.shell: grep -qxF 'nuc1.home:/mnt/storage_disk /mnt/shared_storage nfs defaults 0 0' /etc/fstab || echo 'nuc1.home:/mnt/storage_disk /mnt/shared_storage nfs defaults 0 0' >> /etc/fstab
    