---
- hosts: all
  remote_user: oliver
  # NOTE: Run this with ansible-playbook -become -i home_cluster.ini cluster_packages_u2204.yaml
  # become: true
  # become_method: sudo
  # become_user: root
  tasks:
    - name: Unconditionally reboot the machine with all defaults
      ansible.builtin.reboot: